### PR TITLE
Packager

### PR DESCRIPTION
**Pull request by fpistm**
Hi Roger,
Here a script to generate and update the JSON.
If you could test it and merge if you are ok.
If you have any question do not hesitate.

Scripts features:
	- Generate the tar archive for each core and tools (with or without source (default without)).
	- Update properly the json file (url, name, checksum,size)
	- Add a new platform to the json file if it does not exist.
	- Update the list of supported boards displayed by the Arduino IDE board manager (based on the board.txt)
        - Include the commit info to the package (file package_version.txt) in order to know where it has been created from the git.
BR

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks Frederic

I will try it

**Comment by danieleff** [comment]
I run the script, it seems to override the current version, while the [arduino json](http://downloads.arduino.cc/packages/package_index.json) has an entry for every version.

**Comment by fpistm** [comment]
yes it overrides it.
Doing like Arduino is also possible. I saw some other JSON which do not include all version.
That's a point to discuss. Let me know what you preferred then I will do a updated version of the script if required.

**Comment by Testato** [comment]
Is this board manager for ST core ?
Will be created a Board manager for stm32duino core also ?

Il 15 dic 2016 14:06, "Frederic Pillon" <notifications@github.com> ha
scritto:

**Comment by fpistm** [comment]
Currently, 
the script is able to package the stm32duino git repo;
Arduino_Core_STM32L4
Arduino_Core_STM32F1
Arduino_Tools

It could be updated to manage other core if required to the same JSON file or to another one by adding for example a '-j <json file>'.
Some other update could be required.
ex: arch is partially hardcoded :
local arch=`echo "$1" | tr '[:upper:]' '[:lower:]'`"xx" -->  (ex: stm32f1xx)

It's a proposal and I think a good example on how to create package and JSON file easily.

**Comment by fpistm** [comment]
Hi,
I'am currently work on an updated script to be more generic and which do not override the json file (same as arduino) as @danieleff comment.
So, please do not merge this one.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by fpistm** [comment]
Hi everyone,
My best wishes for this new year.

I've pushed the new script.
It is more generic and is able to deal with another core repo than STM32 one.
    Main features:
    - Add new core family
    - Add new tools version
    - Add new core version
    - Update an existing core version
    
    If new tools version is packaged, it will be used for new core version.
    Else use the latest one known.

I tried with the Arduino_STM32 git repo from Roger github:
Output script example:
$./dopackage.sh -t RCTools 
Generating tools package RCTools-2017.1.4.tar.bz2...done
Adding RCTools tools version 2017.1.4...done
Generating package RCSTM32F3-2017.1.4.tar.bz2 without source...done
Adding new arch rcstm32f3...
###################################################
# Manual update/check should be required
# in the json file for the architecture rcstm32f3
# ex: tools dependencies
###################################################
RCSTM32F3 contains the following boards:
STM32F3Discovery
done
Generating package RCSTM32F1-2017.1.4.tar.bz2 without source...done
Adding new arch rcstm32f1...
###################################################
# Manual update/check should be required
# in the json file for the architecture rcstm32f1
# ex: tools dependencies
###################################################
RCSTM32F1 contains the following boards:
Maple Mini
Maple (Rev 3)
Maple (RET6)
Microduino Core STM32 to Flash
STM Nucleo F103RB (STLink)
Generic STM32F103C series
Generic STM32F103R series
Generic STM32F103T series
Generic STM32F103V series
Generic STM32F103Z series
HYTiny STM32F103TB
Generic GD32F103C series
STM32VLD to FLASH
done
Generating package RCSTM32F4-2017.1.4.tar.bz2 without source...done
Adding new arch rcstm32f4...
###################################################
# Manual update/check should be required
# in the json file for the architecture rcstm32f4
# ex: tools dependencies
###################################################
RCSTM32F4 contains the following boards:
STM32 Discovery F407
STM32F4Stamp F405
Netduino2 F405
done

**Comment by rogerclarkmelbourne** [comment]
Thanks Frederic

I am busy at work this week, but I will try to test at the weekend

**Comment by danieleff** [comment]
After pulling the changes, but before running the script, the .json contains `architecture: stm32f1xx, version: 2016.9.16`, and `architecture: stm32f1, version: 2016.12.23`, and because of this in arduino board manager the `STM32F1xx Boards by ST-Microelectronics` shows up twice. 

Apart from that, and after run the script, seems to be working fine, and adds the new version.

**Comment by fpistm** [comment]
Right @danieleff, it is "normal".
As a first packages was released (1.0.0) I would not just replace it. Because if some people have installed it, this could brought some issue. That's why I have introduced the 1.0.1 packages version with the arch without the 'xx'.
So, in the board manager, we saw 2 versions one for the "stm32f1xx" and one for the "stm32f1".
After introducing new version, it probably could be removed or now if all are agreed :)
Thanks for the test ;)

**Comment by fpistm** [comment]
After some tests, it seems it is confusing to user  to kept the 1.0.0 package.
I will remove it.

**Comment by rogerclarkmelbourne** [comment]
OK

**Pull request merged**
